### PR TITLE
Add mute/unmute functionality

### PR DESCRIPTION
**Pull request by aliat110**
- This PR adds the functionality to mute/unmute the audio while track is running. This can be done by clicking on the icons available on the either side of the volume slider.

Relates #1

### CODE REVIEW

**Comment by aliat110** [comment]
@Rishav-01 does this not solve the muting/unmuting functionality at least?

**Comment by Rishav-01** [comment]
> @Rishav-01 does this not solve the muting/unmuting functionality at least?

Nope Buddy

**Comment by aliat110** [comment]
> Nope Buddy

@Rishav-01 If you click on the either side of the volume up/down slider on the speaker button, it would mute the audio.
image

**Comment by Rishav-01** [comment]
Hey Buddy !

This is not the problem I have stated 
I stated my problem clearly in the [Issue](https://github.com/Rishav-01/Musify-App/tree/main/Issue) folder
@aliat110

**Pull request closed without merging**
